/*CREATE DATABASE ACT_1_T8;*/
USE ACT_1_T8;
CREATE TABLE PUB(
COD_PUB VARCHAR(15) NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
LICENCIA_FISCAL VARCHAR(30) NOT NULL,
DOMICILIO VARCHAR(30) NULL,
FECHA_APERTURA DATE NOT NULL,
HORARIO VARCHAR(20) NOT NULL,
COD_LOCALIDAD INT NOT NULL,
FOREIGN KEY (COD_LOCALIDAD) REFERENCES LOCALIDAD(COD_LOCALIDAD)  
ON UPDATE CASCADE ON DELETE NO ACTION,
PRIMARY KEY(COD_PUB)
);

CREATE TABLE TITULAR
(
DNI_TITULAR CHAR(9) NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
DOMICILIO VARCHAR(30) NULL,
COD_PUB VARCHAR(15) NOT NULL,
FOREIGN KEY (COD_PUB) REFERENCES PUB(COD_PUB)  ON UPDATE CASCADE 
ON DELETE NO ACTION,
PRIMARY KEY (DNI_TITULAR)
);
CREATE TABLE EMPLEADO
(
DNI_EMPLEADO CHAR(9) NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
DOMICILIO VARCHAR(30) NULL,
PRIMARY KEY (DNI_EMPLEADO)
);
CREATE TABLE EXISTENCIAS
(
COD_ARTICULO VARCHAR(9) NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
CANTIDAD INT NOT NULL,
PRECIO FLOAT NOT NULL CHECK(PRECIO > 0),
COD_PUB VARCHAR(15) NOT NULL,
FOREIGN KEY (COD_PUB) REFERENCES PUB (COD_PUB) ON UPDATE CASCADE 
ON DELETE NO ACTION,
PRIMARY KEY (COD_ARTICULO)
);
CREATE TABLE LOCALIDAD
(
COD_LOCALIDAD INT NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
PRIMARY KEY (COD_LOCALIDAD)
);

CREATE TABLE PUB_EMPLEADO
(
COD_PUB VARCHAR(15) NOT NULL,
FOREIGN KEY (COD_PUB) REFERENCES PUB (COD_PUB) ON UPDATE CASCADE 
ON DELETE NO ACTION,
DNI_EMPLEADO CHAR(9) NOT NULL,
FOREIGN KEY(DNI_EMPLEADO) REFERENCES EMPLEADO (DNI_EMPLEADO) ON 
UPDATE CASCADE ON DELETE NO ACTION,
FUNCION ENUM ('CAMARERO', 'SEGURIDAD', 'LIMPIEZA') NOT NULL,
PRIMARY KEY (FUNCION)
);