CREATE DATABASE PUBS;
USE PUBS;
CREATE TABLE LOCALIDAD(
COD_LOCALIDAD INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50) NOT NULL
);
CREATE TABLE EMPLEADO(
DNI_EMPLEADO VARCHAR(9) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
DOMICILIO VARCHAR(100)
);
CREATE TABLE PUB(
COD_PUB VARCHAR(10) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
LICENCIA_FISCAL VARCHAR(20) NOT NULL,
DOMICILIO VARCHAR(50),
FECHA_APERTURA DATE NOT NULL,
HORARIO VARCHAR(4) NOT NULL,
COD_LOCALIDAD INT NOT NULL,
CHECK(HORARIO IN('HOR1','HOR2','HOR3')),
FOREIGN KEY(COD_LOCALIDAD) REFERENCES LOCALIDAD(COD_LOCALIDAD)
);
CREATE TABLE TITULAR(
DNI_TITULAR VARCHAR(9) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
DOMICILIO VARCHAR(50),
COD_PUB VARCHAR(10) NOT NULL,
FOREIGN KEY(COD_PUB) REFERENCES PUB(COD_PUB)
);
CREATE TABLE EXISTENCIAS(
COD_ARTICULO VARCHAR(10) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
CANTIDAD INT NOT NULL,
PRECIO FLOAT NOT NULL,
COD_PUB VARCHAR(10) NOT NULL,
CHECK(PRECIO>0),
FOREIGN KEY(COD_PUB) REFERENCES PUB(COD_PUB)
);
CREATE TABLE PUB_EMPLEADO(
COD_PUB VARCHAR(10) NOT NULL,
DNI_EMPLEADO VARCHAR(9) NOT NULL,
FUNCION VARCHAR(9) NOT NULL,
CHECK(FUNCION IN('CAMARERO','SEGURIDAD','LIMPIEZA')),
PRIMARY KEY(COD_PUB,DNI_EMPLEADO,FUNCION)
);