CREATE DATABASE VENTA;
USE VENTA;
CREATE TABLE CLIENTES(
N_CLIENTE INT(10) PRIMARY KEY NOT NULL,
Nombre varchar(20) NOT NULL,
Direccion varchar(30) NOT NULL,
Ciudad varchar(20) NOT NULL,
Region varchar(20) NOT NULL,
CodPostal int(5) NOT NULL,
Pais varchar(20) NOT NULL,
Telefono int(9) NOT NULL,
Fax int(9) 
);
CREATE TABLE PRODUCTO( 
N_PRODUCTO INT(10) PRIMARY KEY NOT NULL, 
Descripcion VARCHAR(20) NOT NULL, 
Precio_Unidad FLOAT(8) NOT NULL, 
N_PROVEEDOR INT(10) NOT NULL
);
CREATE TABLE EMPLEADO(
N_EMPLE INT(10) PRIMARY KEY NOT NULL,
Cod_Emp INT(10) NOT NULL,
Comentario VARCHAR(40),
Salario FLOAT(7) NOT NULL
);
CREATE TABLE DEPARTAMENTO(
COD INT(10) PRIMARY KEY NOT NULL,
Departamento VARCHAR(20) NOT NULL
);
CREATE TABLE NUM_VENTA(
N_VENTA INT(15) PRIMARY KEY NOT NULL,
FECHA DATE NOT NULL,
N_EMPLE INT(10) NOT NULL,
N_CLIENTE INT(10) NOT NULL,
FOREIGN KEY(N_EMPLE) REFERENCES EMPLEADO(N_EMPLE),
FOREIGN KEY(N_CLIENTE) REFERENCES CLIENTES(N_CLIENTE)
);
CREATE TABLE VENTAS(
N_VENTA INT(8) NOT NULL,
N_PRODUCTO INT(10) NOT NULL,
Cantidad INT(10) NOT NULL,
PRIMARY KEY(N_VENTA,N_PRODUCTO)
);
